import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Providers } from "@/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-300 overflow-hidden`}>
      <GoogleOAuthProvider clientId="534978554754-hvb128secplc5h5rs4gbeg7oo6vhrark.apps.googleusercontent.com">
        <Providers>
            {children}
        </Providers>
      </GoogleOAuthProvider>
      </body>
    </html>
  );
}
